fix: resolve proxy command ssl not working

diff --git a/bin/dktl b/bin/dktl
--- a/bin/dktl
+++ b/bin/dktl
@@ -4,8 +4,9 @@
 # DKAN-tools bash script.                                                      #
 ################################################################################
 
-DKTL_SSL=false
-DKTL_SSL_MAIL="null@example.com"
+## Supported env variables:
+# DKTL_SSL=false
+# DKTL_SSL_MAIL="null@example.com"
 
 # Primary workflow for dktl command. Executed on last line of script.
 main() {
@@ -233,8 +234,8 @@ proxy_setup() {
 
     TRAEFIK_CMD="docker run -d \
       -p 8080:8080 -p 80:80 -p 443:443 \
-      -v '/var/run/docker.sock:/var/run/docker.sock' \
-      --name 'dktl-proxy' \
+      -v /var/run/docker.sock:/var/run/docker.sock \
+      --name dktl-proxy \
       traefik:v2.0"
 
     TRAEFIK_OPTS=" --log.level=INFO \
@@ -242,18 +243,17 @@ proxy_setup() {
       --entrypoints.web.address=:80 \
       --entrypoints.websecure.address=:443"
 
-    if [ $DKTL_SSL ]; then
+    if [ "$DKTL_SSL" = true ]; then
       TRAEFIK_OPTS+=" --certificatesresolvers.letsencrypt.acme.tlschallenge=true \
       --certificatesResolvers.letsencrypt.acme.email=$DKTL_SSL_MAIL \
       --certificatesResolvers.letsencrypt.acme.storage=acme.json"
     fi
 
-    if ! "$TRAEFIK_CMD" "$TRAEFIK_OPTS" \
-      >/dev/null; \
+    if ! $TRAEFIK_CMD $TRAEFIK_OPTS >/dev/null; \
     then
-      echo -n "Failed to start the dktl-proxy container..."
+      echo "Failed to start the dktl-proxy container..."
     else
-      echo -n "dktl-proxy started successfully..."
+      echo "dktl-proxy started successfully..."
     fi
 
   fi
