Update dktl

diff --git a/bin/dktl b/bin/dktl
--- a/bin/dktl
+++ b/bin/dktl
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/bin/sh
 
 ################################################################################
 # DKAN-tools bash script.                                                      #
@@ -13,7 +13,7 @@ main() {
 
   set_project_directory "$@"
   set_slug
-  
+
   if [ "$DKTL_MODE" = "DOCKER" ]; then
     dktl_docker_run "$@"
   elif [ "$DKTL_MODE" = "HOST" ]; then
@@ -26,57 +26,60 @@ dktl_run() {
     # Check whether dkan-tools' dependencies have been initialized.
     if [ -z "$(ls -lha $DKTL_DIRECTORY | grep vendor)" ]; then
       echo "Composer Install"
-      composer install --working-dir=$DKTL_DIRECTORY
+      composer install --working-dir="$DKTL_DIRECTORY"
     fi
 
     # Finally, execute the php app.
+    argument_substring=`echo ${@}|cut -d ' ' -f2-|awk '{$1=$1};1'`
     case $1 in
         # Pass through arguments for these. See: https://bit.ly/30IlWGk
         drush | phpunit | *test* )
-            php "$DKTL_DIRECTORY"/bin/app.php $1 -- "${@:2}"
+	    echo "php $DKTL_DIRECTORY/bin/app.php $1 -- $argument_subtstring"
+	    php "$DKTL_DIRECTORY"/bin/app.php $1 -- "$argument_subtstring"
             ;;
-        *)
-            php "$DKTL_DIRECTORY"/bin/app.php $1 "${@:2}"
+	*)
+	    echo "php $DKTL_DIRECTORY/bin/app.php $1 $argument_subtstring"
+	    php "$DKTL_DIRECTORY"/bin/app.php $1
             ;;
     esac
-
 }
 
 # Execute the dkan-tools app in the CLI container.
 dktl_docker_run() {
   docker_vars_init
-  proxy_setup
+#  proxy_setup
   docker_command_intercept "$@"
   dc_up
   dktl_set_alias
 
   # Proxy-pass to docker and save exit status. The command will re-
   # run in host mode inside the cli container, so dktl_run will still
-  # ultimately be run whichever mode dktl is set to. 
-  dc_base exec $EXEC_OPTS cli dktl "$1" "${@:2}"
+  # ultimately be run whichever mode dktl is set to.
+  dc_base exec "$EXEC_OPTS" cli dktl "$1" "$2"
   exit_status=$?
 
   dktl_docker_cleanup "$@"
 
-  # if we encountered a non-zero exit status during the docker exec, 
+  # if we encountered a non-zero exit status during the docker exec,
   # pass it on.
   if [ $exit_status -ne 0 ]; then
     exit $exit_status
   fi
 }
 
-# Set DKTL_PLATFORM to which platform we're running on (linux and mac 
+# Set DKTL_PLATFORM to which platform we're running on (linux and mac
 # supported)
 set_platform() {
-  if [ -z $PLATFORM ]; then
-    export PLATFORM=`uname`
+  if [ -z "$PLATFORM" ]; then
+    PLATFORM=$(uname)
+    export PLATFORM
   fi
 }
 
-# Set DKTL_MODE. Determine whether we want to run inside the docker container 
+# Set DKTL_MODE. Determine whether we want to run inside the docker container
 # or in the host machine.
 set_mode() {
-  if [ -z $DKTL_MODE ] || [ "$DKTL_MODE" = "DOCKER" ]; then
+  if [ -z "$DKTL_MODE" ] || [ "$DKTL_MODE" = "DOCKER" ]; then
     DKTL_MODE="DOCKER"
   elif [ "$DKTL_MODE" = "HOST" ]; then
     DKTL_MODE="HOST"
@@ -89,12 +92,12 @@ set_mode() {
 # Check dkan-tools dependencies, exit if unmet
 check_dependencies() {
   if [ "$DKTL_MODE" = "DOCKER" ]; then
-    if [ -z `which docker` ] || [ -z `which docker-compose` ]; then
+    if [ -z "$(which docker)" ] || [ -z "$(which docker-compose)" ]; then
         echo "docker and docker-compose are required. Exiting."
         exit 1
     fi
   else
-    if [ -z `which php` ] || [ -z `which composer` ]; then
+    if [ -z "$(which php)" ] || [ -z "$(which composer)" ]; then
       echo "php and composer are required. Exiting."
       exit 1
     fi
@@ -106,7 +109,7 @@ set_project_directory() {
   # Find project root so we can run from anywhere
   find_up () {
     path=$(pwd)
-    while [[ "$path" != "" && ! -e "$path/$1" ]]; do
+    while [ "$path" != "" ] && [ ! -e "$path/$1" ]; do
       path=${path%/*}
     done
     echo "$path"
@@ -128,7 +131,7 @@ set_project_directory() {
 set_directory() {
   DKTL_DIRECTORY=$(which dktl)
 
-  if [[ -L $(which dktl) ]]; then
+  if [ -L "$(which dktl)" ]; then
     # readlink command needs -f to work properly in linux
     if [ "$PLATFORM" = "Linux" ]; then RL_OPT='-f'; fi;
     DKTL_DIRECTORY=$(readlink $RL_OPT "$DKTL_DIRECTORY")
@@ -145,10 +148,10 @@ set_directory() {
 set_slug() {
   if [ -z "$DKTL_SLUG" ]; then
     DKTL_SLUG=${DKTL_PROJECT_DIRECTORY##*/}
-    DKTL_SLUG=${DKTL_SLUG//-/}
-    DKTL_SLUG=${DKTL_SLUG//_/}
+    DKTL_SLUG=$(printf '%s' "$DKTL_SLUG" | tr '' '-')
+    DKTL_SLUG=$(printf '%s' "$DKTL_SLUG" | tr '' '_')
     # Mixed case dirs cause issue with docker image names
-    DKTL_SLUG=$(echo ${DKTL_SLUG} | tr -d '[:space:]' | tr "[A-Z]" "[a-z]")
+    DKTL_SLUG=$(echo "${DKTL_SLUG}" | tr -d '[:space:]' | tr "[A-Z]" "[a-z]")
     export DKTL_SLUG
   fi
 }
@@ -156,10 +159,10 @@ set_slug() {
 # Set the following variables for use with docker-compose commands:
 # DKTL_PROXY_DOMAIN, BASE_DOCKER_COMPOSE_COMMAND, EXEC_OPTS
 docker_vars_init() {
-  if [ -z $WEB_DOMAIN ]; then
+  if [ -z "$WEB_DOMAIN" ]; then
     WEB_DOMAIN="localtest.me"
   fi
-  if [ -z $DKTL_PROXY_DOMAIN ]; then
+  if [ -z "$DKTL_PROXY_DOMAIN" ]; then
     export DKTL_PROXY_DOMAIN="$DKTL_SLUG.$WEB_DOMAIN"
   fi
 
@@ -167,7 +170,7 @@ docker_vars_init() {
   OVERRIDES_CONF="$DKTL_PROJECT_DIRECTORY/src/docker/docker-compose.overrides.yml"
 
   # Check for interactive shell if DKTL_NO_PTY is not set
-  if [ ! -z "$DKTL_NO_PTY" ]; then
+  if [ -n "$DKTL_NO_PTY" ]; then
     EXEC_OPTS='-T'
   elif [ -t 1 ]; then
     EXEC_OPTS=''
@@ -177,17 +180,18 @@ docker_vars_init() {
 }
 
 dc_base() {
-  dc=( docker-compose \
-    --file "$COMMON_CONF" \
+  dc="docker-compose \
+    --file $COMMON_CONF \
     --project-name $DKTL_SLUG \
-    --project-directory "$DKTL_PROJECT_DIRECTORY" )
+    --project-directory $DKTL_PROJECT_DIRECTORY"
 
   if [ -f "$OVERRIDES_CONF" ]; then
-    dc+=( --file "$OVERRIDES_CONF" )
+    dc="$dc --file $OVERRIDES_CONF"
   fi
 
-  dc+=( "$@" )
-  "${dc[@]}"
+  dc="$dc $@"
+#  "${dc[@]}"
+  eval "$dc"
 }
 
 
@@ -206,7 +210,7 @@ dc_up () {
   if [ -z "$containers" ]; then
     echo "Starting docker containers."
     dc_base up -d
-    proxy_connect
+##    proxy_connect
   fi
 }
 
@@ -217,13 +221,13 @@ dc_down() {
     echo "Disconnected dktl-proxy from \"${network}\" network."
   fi
 
-  dc_base down -v "${@:2}"
+  dc_base down -v "${@#??}"
 }
 
 # Make sure the proxy container is up.
 proxy_setup() {
   proxy_service_ps=$(docker ps -f 'name=dktl-proxy' --format '{{.Names}}' 2>/dev/null)
-  if [[ -z $proxy_service_ps ]]; then
+  if [ -z "$proxy_service_ps" ]; then
     echo "Running dktl-proxy.."
     # Make sure no old instance is using the name.
     docker rm dktl-proxy >/dev/null 2>&1
@@ -236,7 +240,7 @@ proxy_setup() {
       --entrypoints.websecure.address=:443 \
       >/dev/null; \
     then
-      echo -n "Failed to start the dktl-proxy container..."
+      echo "Failed to start the dktl-proxy container..."
     fi
 
   fi
@@ -246,7 +250,7 @@ proxy_setup() {
 docker_command_intercept() {
   if [ "$1" = "docker:compose" ] || [ "$1" = "dc" ]; then
     dc_up
-    dc_base "${@:2}"
+    dc_base "${@#??}"
     exit 0
   elif [ "$1" = "url" ] || [ "$1" = "docker:url" ]; then
     echo "http://$DKTL_PROXY_DOMAIN"
@@ -255,7 +259,7 @@ docker_command_intercept() {
     dc_down
     exit 0
   elif [ "$1" = "docker:proxy-connect" ] || [ "$1" = "proxy:connect" ]; then
-    proxy_connect
+##    proxy_connect
     # Restart container to refresh config.
     dc_base restart
     exit 0
@@ -280,21 +284,21 @@ dktl_set_alias() {
 
 dktl_docker_cleanup() {
   # Reset web and cli containers if xdebug.
-  if [ $? -eq 0 ] && [[ $1 == "xdebug"* ]]; then
+  if [ "$?" -eq 0 ] && [ "$1" = "xdebug"* ]; then
     dc_base restart web
     dc_base restart cli
   fi
 
   # Proxy connect if we just ran make.
-  if [ $? -eq 0 ] && [[ $1 == "init"* ]]; then
-    proxy_connect
+  if [ "$?" -eq 0 ] && [ "$1" = "init"* ]; then
+##    proxy_connect
     dc_base restart web
   fi
 
   if [ -z "$DKTL_CHOWN" ] || [ "$DKTL_CHOWN" = "TRUE" ]; then
     # Docker creates files that appear as owned by root on host. Fix:
     if [ -n "$(find "$DKTL_PROJECT_DIRECTORY" -user root -print -quit)" ]; then
-        dc_base exec $EXEC_OPTS cli chown -R `id -u`:`id -g` /var/www
+        dc_base exec "$EXEC_OPTS" cli chown -R "$(id -u)":"$(id -g)" /var/www
     fi
   fi
 }
